services:
  neko:
    image: "ghcr.io/m1k1o/neko/chromium:latest"
    restart: "unless-stopped"
    shm_size: "2gb"
    cap_add:
      - SYS_ADMIN
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.neko-frontend.loadbalancer.server.port=8080"
      - "traefik.http.routers.neko.rule=${TRAEFIK_RULE}"
      - "traefik.http.routers.neko.entrypoints=${TRAEFIK_ENTRYPOINTS}"
      - "traefik.http.routers.neko.tls.certresolver=${TRAEFIK_CERTRESOLVER}"
    ports:
      - "8080:8080"
      - "52000-52100:52000-52100/udp"
